name: 'notify-slack-action'
description: 'Send a message to Slack'
author: 'Tise'
inputs:
    token:
        required: true
        description: 'Slack token to use'
    actor:
        required: false
        description: 'Github user that triggered action'
    event:
        required: false
        description: 'What happened (comes after the subject)'
    subject:
        required: false
        description: 'Thing that something happened to (will link to run)'
    include_ref:
        required: false
        description: 'Include ref in title'
        default: true
    threaded_message:
        required: false
        description: 'Message to send in a threaded message'
    mention:
        required: false
        description: 'Mention a group (e.g. here)'
    title:
        required: false
        description: 'Instead of setting event & subject, set a custom title'
    message:
        required: false
        description: 'Message body'
    icon_emoji:
        required: false
        description: 'Emoji to use as sender avatar'
    username:
        required: false
        description: 'User to user as sender'
        default: 'GitHub'
    channel:
        required: true
        description: 'Channel to send to'
    color:
        required: false
        description: 'Status color to use'
        default: 'good'
    footer:
        required: false
        description: "Footer to include. Defaults to the repo's name"
    text:
        required: false
        description: 'Text to send'

runs:
    using: 'node20'
    main: 'dist/index.js'
