name: 'notify-slack-action'
description: 'Send a message to Slack'
author: 'TIse'
inputs:
    webhook:
        required: true
        description: 'Slack webhook to use'
    actor:
        required: false
        description: 'Github user that triggered action'
    event:
        required: false
        description: 'What happened (comes after the subject)'
    subject:
        required: false
        description: 'Thing that something happened to (will link to run)'
    mention:
        required: false
        description: 'Mention a group (e.g. here)'
    title:
        required: false
        description: 'Instead of setting event & subject, set a custom title'
    message:
        required: false
        description: 'Message body'
    iconEmoji:
        required: false
        description: 'Emoji to use as sender avatar'
    username:
        required: false
        description: 'User to user as sender'
        default: 'GitHub'
    channel:
        required: false
        description: 'Channel to send to'
    color:
        required: false
        description: 'Status color to usi'
        default: 'good'
    footer:
        required: false
        description: 'Footer to include'
        default: 'Repo name'
runs:
    using: 'node12'
    main: 'dist/index.js'
